---
- hosts: all
  tasks:
    - name: ensure nginx is at the latest version
      apt: name=nginx state=latest
      become: yes
    - name: start nginx
      service:
          name: nginx
          state: started
      become: yes
    - name: ensure certbot is at the latest version
      apt: 
          name: python-certbot-nginx
      become: yes
    - name: restart nginx
      service:
        name: nginx
        state: restarted
      become: yes