---
- name: change DNS server
  when: not ansible_windows_domain_member
  win_dns_client:
    adapter_names: '*'
    ipv4_addresses: 
      - 10.0.1.99
      - 168.63.129.16


- name: join domain
  win_domain_membership:
    dns_domain_name: 'corph.mouradcloud.com'
    domain_admin_user: 'administrator@corph.mouradcloud.com'
    domain_admin_password: 'M0nP@ssw0rd!'
    state: domain
  register: domain_joined

- name: reboot after domain join
  win_reboot:
  when: domain_joined.reboot_required

- name: Wait for system to become reachable over WinRM
  wait_for_connection:
    timeout: 900

- name: install ad
  win_domain_controller:
    dns_domain_name: 'corph.mouradcloud.com'
    domain_admin_user: 'administrator@corph.mouradcloud.com'
    domain_admin_password: 'M0nP@ssw0rd!'
    safe_mode_password: 'M0nP@ssw0rd!'
    state: domain_controller
  register: ad

- name: reboot server
  win_reboot:
    msg: "Installing AD. Rebooting..."
    pre_reboot_delay: 15
  when: ad.changed
