preferred-location-main = "__preferred-location-main__"
second-location-main = "__second-location-main__"
current-name-convention-core-main = "__current-name-convention-core-main__"
current-name-convention-core-public-main = "__current-name-convention-core-public-main__"

current-vnet-space = "__current-vnet-space__"

current-vm-default-username-main = "__current-vm-default-username-main__"
current-vm-default-pass-main = "__current-vm-default-pass-main__"

privatedmzin-root-name = "__privatedmzin-root-name__"
subnet-privatedmzin = "__subnet-privatedmzin__"
nsg-privatedmzin = "__nsg-privatedmzin__"
privatedmzoutlan-root-name = "__privatedmzoutlan-root-name__"
subnet-privatedmzoutlan = "__subnet-privatedmzoutlan__"
nsg-privatedmzoutlan = "__nsg-privatedmzoutlan__"

mt-area-dc-dns-private-ip-address = "__mt-area-dc-dns-private-ip-address__"
security-appliance-dmz-private-ip-address-in = "__security-appliance-dmz-private-ip-address-in__"
security-appliance-dmz-private-ip-address-out = "__security-appliance-dmz-private-ip-address-out__"
mt-root-name = "__mt-root-name__"
subnet-mt = "__subnet-mt__"
nsg-mt-1 = "__nsg-mt-1__"
nsg-mt-2 = "__nsg-mt-2__"
nsg-mt-3 = "__nsg-mt-3__"
mt-vm-private-ip-address = "__mt-vm-private-ip-address__"
mtl-vm-private-ip-address = "__mtl-vm-private-ip-address__"
publicdmzin-root-name = "__publicdmzin-root-name__"
subnet-publicdmzin = "__subnet-publicdmzin__"
nsg-publicdmzin-1 = "__nsg-publicdmzin-1__"
nsg-publicdmzin-2 = "__nsg-publicdmzin-2__"
GatewaySubnet-root-name = "__GatewaySubnet-root-name__"
subnet-GatewaySubnet = "__subnet-GatewaySubnet__"
nsg-GatewaySubnet-1 = "__nsg-GatewaySubnet-1__"
nsg-GatewaySubnet-2 = "__nsg-GatewaySubnet-2__"
nsg-GatewaySubnet-3 = "__nsg-GatewaySubnet-3__"
nsg-GatewaySubnet-4 = "__nsg-GatewaySubnet-4__"
iprange-onprem-vpn = "__iprange-onprem-vpn__"
ipaddress-routeur-onprem-1-azuredevops = "__ipaddress-routeur-onprem-1-azuredevops__"
waf-vm-private-public-ip-address = "__waf-vm-private-public-ip-address__"
tf_storage_account_key = "__tf_storage_account_key__"